#!/usr/bin/env bash
# charmcraft-purge
# @describe Delete all the LXC instances that charmcraft creates to pack charms
# @author Luca Bello
# @meta version 0.3
# @meta require-tools lxc,jq

# @option --last-used Delete instances that were last use before this date (format: anything parsed by 'date') (default: one month ago)
# @flag --dry-run Perform a dry run (don't delete instances)

eval "$(argc --argc-eval "$0" "$@")"

# Default --last-used to one week ago (if not specified)
if [[ -z $argc_last_used ]]; then
  argc_last_used="$(date -d '-7 days' +'%F')";
else
  argc_last_used="$(date -d "$argc_last_used" +'%F')"
fi

lxc_instances=$(lxc list --project=charmcraft --format=json | jq --arg cutoff "$argc_last_used" '[.[] | select(.last_used_at | . < $cutoff)]')
lxc_instances_count=$(echo "$lxc_instances" | jq -r '[ .[] | select(.name | startswith("charmcraft-")) | .name ] | length')
echo "$lxc_instances_count lxc containers will be removed (not used since $argc_last_used)"
for instance in $(echo $lxc_instances | jq -r '.[] | select(.name | startswith("charmcraft-")) | .name'); do
  echo "Deleting $instance"
  if [ "$argc_dry_run" = 0 ]; then
    lxc --project=charmcraft delete "$instance"
  fi
done
